//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSConsoleApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateWayProvider", Namespace="http://schemas.datacontract.org/2004/07/Tpo.Notification")]
    [System.SerializableAttribute()]
    public partial class GateWayProvider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderIdField, value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsAddress {
            get {
                return this.SmsAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsAddressField, value) != true)) {
                    this.SmsAddressField = value;
                    this.RaisePropertyChanged("SmsAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSMessage", Namespace="http://schemas.datacontract.org/2004/07/Tpo.Notification")]
    [System.SerializableAttribute()]
    public partial class SMSMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime scheduledDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromAddress {
            get {
                return this.fromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.fromAddressField, value) != true)) {
                    this.fromAddressField = value;
                    this.RaisePropertyChanged("fromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromName {
            get {
                return this.fromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fromNameField, value) != true)) {
                    this.fromNameField = value;
                    this.RaisePropertyChanged("fromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime scheduledDateTime {
            get {
                return this.scheduledDateTimeField;
            }
            set {
                if ((this.scheduledDateTimeField.Equals(value) != true)) {
                    this.scheduledDateTimeField = value;
                    this.RaisePropertyChanged("scheduledDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string textBody {
            get {
                return this.textBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.textBodyField, value) != true)) {
                    this.textBodyField = value;
                    this.RaisePropertyChanged("textBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toAddress {
            get {
                return this.toAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.toAddressField, value) != true)) {
                    this.toAddressField = value;
                    this.RaisePropertyChanged("toAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Tpo.Notification")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITPONotification")]
    public interface ITPONotification {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPONotification/GetGateWayProviders", ReplyAction="http://tempuri.org/ITPONotification/GetGateWayProvidersResponse")]
        SMSConsoleApplication.ServiceReference1.GetGateWayProvidersResponse GetGateWayProviders(SMSConsoleApplication.ServiceReference1.GetGateWayProvidersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPONotification/SendAlert", ReplyAction="http://tempuri.org/ITPONotification/SendAlertResponse")]
        SMSConsoleApplication.ServiceReference1.SendAlertResponse SendAlert(SMSConsoleApplication.ServiceReference1.SendAlertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGateWayProviders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGateWayProvidersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        public GetGateWayProvidersRequest() {
        }
        
        public GetGateWayProvidersRequest(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGateWayProvidersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGateWayProvidersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSConsoleApplication.ServiceReference1.GateWayProvider[] GetGateWayProvidersResult;
        
        public GetGateWayProvidersResponse() {
        }
        
        public GetGateWayProvidersResponse(SMSConsoleApplication.ServiceReference1.GateWayProvider[] GetGateWayProvidersResult) {
            this.GetGateWayProvidersResult = GetGateWayProvidersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAlert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAlertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SMSConsoleApplication.ServiceReference1.SMSMessage sms;
        
        public SendAlertRequest() {
        }
        
        public SendAlertRequest(string token, SMSConsoleApplication.ServiceReference1.SMSMessage sms) {
            this.token = token;
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAlertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAlertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSConsoleApplication.ServiceReference1.Response SendAlertResult;
        
        public SendAlertResponse() {
        }
        
        public SendAlertResponse(SMSConsoleApplication.ServiceReference1.Response SendAlertResult) {
            this.SendAlertResult = SendAlertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITPONotificationChannel : SMSConsoleApplication.ServiceReference1.ITPONotification, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPONotificationClient : System.ServiceModel.ClientBase<SMSConsoleApplication.ServiceReference1.ITPONotification>, SMSConsoleApplication.ServiceReference1.ITPONotification {
        
        public TPONotificationClient() {
        }
        
        public TPONotificationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPONotificationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPONotificationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPONotificationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMSConsoleApplication.ServiceReference1.GetGateWayProvidersResponse GetGateWayProviders(SMSConsoleApplication.ServiceReference1.GetGateWayProvidersRequest request) {
            return base.Channel.GetGateWayProviders(request);
        }
        
        public SMSConsoleApplication.ServiceReference1.SendAlertResponse SendAlert(SMSConsoleApplication.ServiceReference1.SendAlertRequest request) {
            return base.Channel.SendAlert(request);
        }
    }
}
